owner: kisodev
repo: status

sites:
  - name: WitAqua
    url: https://witaqua.org
    assignees:
      - soralis0912
      - neroices
  - name: WitAqua Wiki
    url: https://wiki.witaqua.org
    assignees:
      - soralis0912
      - neroices
  - name: WitAqua Gerrit
    url: https://gerrit.witaqua.org
    assignees:
      - soralis0912
      - neroices
  - name: WitAqua Pasty
    url: https://paste.witaqua.org
    assignees:
      - soralis0912
      - neroices
  - name: Kisodev Status
    url: https://status.dev.slce.moe
    assignees:
      - soralis0912
      - neroices
  - name: WitAqua Test
    url: https://test.witaqua.org
    assignees:
      - neroices

status-website:
  cname: status.dev.slce.moe
  logoUrl: https://github.com/kisodev.png
  name: Kiso Status
  introTitle: ヽ(・∀・)ﾉ
  introMessage: Hello, World!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

commitMessages:
  commitAuthorName: "github-actions[bot]"
  commitAuthorEmail: "github-actions[bot]@users.noreply.github.com"
